### ISSUE TITLE
Very high memory consumption compilation

### ISSUE THREAD

**Issue by mr-eyes** [atom-moyer/getpy#2]
Hi,
Thanks for the efforts in wrapping the [parallel-hashmap](https://github.com/greg7mdp/parallel-hashmap).

It took about 25 GB of memory to compile the Python interface, is that should be considered as an expected behavior when compiling a pybind11-based Python interface?

What causes that memory consumption and how to avoid it? ordinary computers can't afford the computational power needed for just the compilation.

I also suggest using [Manylinux](https://github.com/pypa/manylinux) to produce generic python wheels to be easily distributed on Pypi, that will avoid the compilation itself.

Thanks.

**Comment by atom-moyer** [comment]
Hi,

I am aware that the memory consumption is too high during compilation for typical computer systems.

I have not debugged which part requires the memory. I suspect that it is because I declare the whole python module (and all of the custom numpy dtypes in one line of code https://github.com/atom-moyer/getpy/blob/2602d0547035cc946066b388bfd144dbabeb1dfa/src/getpy_types.cpp#L50)

I do want to setup the system that creates the wheels on pypi. That is the next thing I plan to do with this project. I will look into Manylinux.

For now, a way to work around the high memory consumption is the reduce the amount of dictionary types that are compiled by reruning the build.py script with some of the dtypes commented out. The byte array datatypes are certainly not necessary for most people. I have created those with the plan of supporting arbitrary dtypes on the fly via view casting.

Adam

**Comment by atom-moyer** [comment]
Hi,

I have figured out how to use docker and manylinux. Feel free to try to install from PyPi now. Let me know if you have any issues with that, but my tests seem good.

Adam

**Comment by mr-eyes** [comment]
@atom-moyer Hi, thanks for getting back to the issue, that's really cool! I'm glad that you managed to get it done.

I have a little question, how did you compile C++17 on manylinux?

**Comment by atom-moyer** [comment]
Yeah the manylinux2014 image has a newer version of gcc.
