### ISSUE TITLE
Add support for serialization other than to disk

### ISSUE THREAD

**Issue by virtualluke** [atom-moyer/getpy#5]
It would be nice to be able to serialize/deserialize objects outside of the filesystem to say a byte array that then can be used for example in an object store storage.  Just as there is now a dump and load method, suggest a dumps and loads function as that seems to be the convention in many of the serialization libraries (ie json.dumps, json.loads).

thanks,
Luke

**Comment by atom-moyer** [comment]
I did not do that because I figured that using `Dict.items()` and serializing the numpy arrays would be just as good as a json file. The binary format serialization is privileged because it avoids some of the overhead of hash table population from two arrays. Realistically, they are very comparable in speed anyways.
